### ISSUE TITLE
In-game chat doesn't show up in teamspeak

### ISSUE THREAD

**Issue by zac198969** [rogermb/BukkitSpeak#5]
We have narrowed down whats causing this, it's Factions, but we don't know why. We use Factions version 1.6.9.4 - but we have tested it with 1.8.0, which didn't work either. Everything else works perfectly fine, just no in-game -> teamspeak chat.

**Comment by rogermb** [comment]
So when you disabled / removed Factions everything worked as it should?

EDIT: And with Factions enabled, are there stack traces or BukkitSpeak error messages in the log?

**Comment by zac198969** [comment]
That is correct.

**Comment by rogermb** [comment]
Okay, I'm assuming you have chatTagRelationColored in your Factions config enabled.
Therefore Factions cancels the chat event and sends out a different message to every single player.

The problem is that BukkitSpeak doesn't listen to cancelled events because, well, cancelled events aren't meant to be sent, like because a player has been muted.

Quick fix: Disable chatTagRelationColored in your config file.
I honestly don't know another way to resolve this without causing problems with other plugins that might cancel the chat events.

**Comment by rogermb** [comment]
Just had an idea, how about I add a config setting to manage with which priority the chat listener is registered?
It's not a perfectly clean solution, but it would be a way to resolve this issue.

**Comment by zac198969** [comment]
Yeah that would be fine. Appreciate it my man. Thanks for your work!

**Comment by rogermb** [comment]
Can you download [build 158](http://jenkins.stutzfam.ch/job/BukkitSpeak/158/), set ChatListenerPriority (should be added to your config file automatically) to NORMAL and test whether the messages get sent again?

**Comment by rogermb** [comment]
Does the chat sending now work properly?

**Comment by rogermb** [comment]
By the way, I don't think BukkitSpeak works with Factions v1.8.x at the moment, but it should be fine with 1.6.9.x.
